### ISSUE TITLE
Problem with installing pkg-resources from requirements.txt [1]

### ISSUE THREAD

**Issue by mrtarsa** [alena-bartosh/speaking-eye#1]
Wanted to track my work activity with speaking-eye and found some issues while installing it.

**Problem:**

Installed system dependencies but got error from setup command.

```
$ git clone https://github.com/alena-bartosh/speaking-eye.git && \
    cd speaking-eye && \
    python3 -m venv .env && \
    source .env/bin/activate && \
    pip install --upgrade pip && \
    pip install -r requirements.txt
```
> ...
> ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 3)) (from versions: none)
> ERROR: No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 3))

**Solution:**

In order to resolve this issue I removed `pkg-resources==0.0.0` from `requirements.txt`

**Environment:**

```
$ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.1
DISTRIB_CODENAME=tessa
DISTRIB_DESCRIPTION="Linux Mint 19.1 Tessa"
```
```
$ python3
>>> import sys; print(sys.version)
3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
```

**Comment by alena-bartosh** [comment]
I installed a fresh `LinuxMint` system and could not reproduce this problem while running commands from `Setup` section. 
```
$ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.3
DISTRIB_CODENAME=tricia
DISTRIB_DESCRIPTION="Linux Mint 19.3 Tricia"
```
So could you provide more information if this issue is still relevant for you?

**Comment by alena-bartosh** [comment]
Closed because no response was received.

**Comment by alena-bartosh** [comment]
This issue has been reproduced on [CI](https://github.com/alena-bartosh/speaking-eye/runs/819776372?check_suite_focus=true#step:4:17). 

Therefore, reopened.
