### ISSUE TITLE
Problem with installing pycairo dependencies from requirements.txt [2]

### ISSUE THREAD

**Issue by mrtarsa** [alena-bartosh/speaking-eye#2]
Wanted to track my work activity with speaking-eye and found some issues while installing it.

**Problem:**

After removed `pkg-resources` (https://github.com/alena-bartosh/speaking-eye/issues/1) from `requirements.txt` I got next error while building `pycairo` dependencies

```
$ git clone https://github.com/alena-bartosh/speaking-eye.git && \
    cd speaking-eye && \
    python3 -m venv .env && \
    source .env/bin/activate && \
    pip install --upgrade pip && \
    pip install -r requirements.txt
```
> ...
> ERROR: Command errored out with exit status 1: /home/tas/Workspace/speaking-eye/.env/bin/python3 /home/tas/Workspace/speaking-eye/.env/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-qk6wrbri/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel pycairo Check the logs for full command output.

**Solution:**

In order to resolve this issue I installed missing system dependency with `sudo apt-get install libcairo2-dev`

**Environment:**

```
$ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.1
DISTRIB_CODENAME=tessa
DISTRIB_DESCRIPTION="Linux Mint 19.1 Tessa"
```
```
$ python3
>>> import sys; print(sys.version)
3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
```

**Comment by alena-bartosh** [comment]
Fixed. Thank you for your interest in speaking-eye 🙃
